### ISSUE TITLE
import error after install

### ISSUE THREAD

**Issue by C-o-m-o-n** [C-o-m-o-n/fake_profile#1]
I successfully installed the package 

```bash
pip install fake-profile==0.1.0
Defaulting to user installation because normal site-packages is not writeable
Collecting fake-profile==0.1.0
  Downloading fake_profile-0.1.0-py3-none-any.whl.metadata (474 bytes)
Requirement already satisfied: Faker in ./.local/lib/python3.11/site-packages (from fake-profile==0.1.0) (26.3.0)
Requirement already satisfied: python-dateutil>=2.4 in /usr/lib/python3/dist-packages (from Faker->fake-profile==0.1.0) (2.9.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.4->Faker->fake-profile==0.1.0) (1.16.0)
Downloading fake_profile-0.1.0-py3-none-any.whl (13 kB)
Installing collected packages: fake-profile
Successfully installed fake-profile-0.1.0
```
But I get this error when I try to import it

```bash
>>> from fake_profile import Xprofile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fake_profile'
>>> 
```

**Comment by c2-tlhah** [comment]
![Screenshot 2024-08-12 132309](https://github.com/user-attachments/assets/97f8a19e-1ea3-49f1-81ca-af26dbee1808)


It worked on python 3.11.7 maybe there is issue with your python version or any other issue with your system. It works just fine.

**Comment by C-o-m-o-n** [comment]
> ![Screenshot 2024-08-12 132309](https://github.com/user-attachments/assets/97f8a19e-1ea3-49f1-81ca-af26dbee1808)
> 
> 
> It worked on python 3.11.7 maybe there is issue with your python version or any other issue with your system. It works just fine.

The error is in the previous version of the package: 
fake-profile==0.1.0
It has been fixed in the new version:
fake-profile==0.2.0
That's a good observation :)
